<a href="<?php echo App::config("url") ?>">Index</a><hr />

<?php if( Session::getInstance()->isLoggedIn() &&
    $post->getUserid()==Session::getInstance()->getUser()->id): ?>
        <a href="<?php echo App::config("url") ?>admin/delete/<?php echo $post->getId() ?>">Delete posts (and all likes, comments and tags)</a><br />
<?php endif; ?><br />

<cite><?= htmlspecialchars($post->getUser()) ?></cite>  <?php echo $post->date ?><br /><br />
<cite><?php echo $post->getLikes() ?> likes</cite><br />
<cite><?php echo $post->getDislikes() ?> dislikes</cite>


<h3>Comments</h3>
<?php foreach ($post->getComments() as $comment): ?>
    <p>
        <cite><?= htmlspecialchars($comment->user) ?></cite>
        <?php echo $comment->date ?><br />
        <?php echo $comment->content ?>
    </p>
<?php endforeach; ?>
<h3>Tags</h3>
<?php foreach ($post->getTags() as $tags): ?>
    <p>
        <?php echo $tags->name ?>
    </p>
<?php endforeach; ?>

<a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button"
   data-show-count="false">Tweet</a><br/>

<div style="vertical-align: top;" class="fb-share-button"
     data-href="<?= App::config('url'). 'Index/view/'.$post->getId()?>"
     data-layout="button" data-size="small" data-mobile-iframe="true">
    <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse"
       class="fb-xfbml-parse-ignore">Share</a>
</div>

<?php if( Session::getInstance()->isLoggedIn() ): ?>

    <form method="post" action="<?php echo App::config('url') ?>admin/comment/<?php echo $post->getId() ?>">

    <div class="form-group">
            <label for="content">New comment: </label>
            <input id="content" name="content">
        </div>

        <button type="submit" class="btn btn-primary">Add comment</button>

    </form><br /><br />

    <form method="post" action="<?php echo App::config('url') ?>admin/tag/<?php echo $post->getId() ?>">

        <div class="form-group">
            <label for="name">New tag: </label>
            <input id="name" name="name">
        </div>

        <button type="submit" class="btn btn-primary">Add tag</button>

    </form>
<?php endif; ?>

<script>(function(d, s, id) {
        let js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.2';
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


